# Generated by Django 4.1.4 on 2023-04-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="create",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="updates",
            new_name="updated",
        ),
        migrations.RemoveField(
            model_name="category",
            name="price",
        ),
    ]
